// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPxsAuZUltx1sDIGKjHinAhMStX3ypnfs',
    appId: '1:396742496948:android:9ea080eb03e70ab4cebde1',
    messagingSenderId: '396742496948',
    projectId: 'chatreto3mt',
    databaseURL: 'https://chatreto3mt-default-rtdb.firebaseio.com',
    storageBucket: 'chatreto3mt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD60JwV8G_5Hg6ABRdeOq-NKkA8x7-tdlQ',
    appId: '1:396742496948:ios:af7d70dfdfdeb5a0cebde1',
    messagingSenderId: '396742496948',
    projectId: 'chatreto3mt',
    databaseURL: 'https://chatreto3mt-default-rtdb.firebaseio.com',
    storageBucket: 'chatreto3mt.appspot.com',
    iosClientId: '396742496948-g58mdrjeja8tr3eo7873noa1rd717kir.apps.googleusercontent.com',
    iosBundleId: 'com.example.fChatTemplate',
  );
}
